//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_BookstoreManagement.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Receipts = new HashSet<Receipt>();
        }
    
        public string EmplId { get; set; }
        public string EmplName { get; set; }
        public string EmplDegree { get; set; }
        public string EmplPosition { get; set; }
        public string EmplAddress { get; set; }
        public string EmplPhone { get; set; }
        public string EmplUsername { get; set; }
        public string EmplPassword { get; set; }
        public bool Status { get; set; }
    
        public virtual Degree Degree { get; set; }
        public virtual Position Position { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipts { get; set; }
    }
}
